[build]
  base = "apps/api"
  functions = "netlify/functions"
  command = "npm run build"  # or your build command inside apps/api

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
